# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/decrypt_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_decrypt(object):
    def setupUi(self, decrypt):
        decrypt.setObjectName("decrypt")
        decrypt.resize(667, 343)
        self.gridLayout_2 = QtWidgets.QGridLayout(decrypt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.decrypt_file = QtWidgets.QPushButton(decrypt)
        self.decrypt_file.setObjectName("decrypt_file")
        self.gridLayout_2.addWidget(self.decrypt_file, 4, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(decrypt)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.reset = QtWidgets.QPushButton(decrypt)
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 3, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(decrypt)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.private_key = QtWidgets.QLineEdit(decrypt)
        self.private_key.setDragEnabled(True)
        self.private_key.setClearButtonEnabled(True)
        self.private_key.setObjectName("private_key")
        self.gridLayout.addWidget(self.private_key, 3, 1, 1, 1)
        self.ofile = QtWidgets.QLineEdit(decrypt)
        self.ofile.setDragEnabled(True)
        self.ofile.setClearButtonEnabled(True)
        self.ofile.setObjectName("ofile")
        self.gridLayout.addWidget(self.ofile, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(decrypt)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.browse_private_Key = QtWidgets.QPushButton(decrypt)
        self.browse_private_Key.setObjectName("browse_private_Key")
        self.gridLayout.addWidget(self.browse_private_Key, 3, 2, 1, 1)
        self.password = QtWidgets.QLineEdit(decrypt)
        self.password.setEchoMode(QtWidgets.QLineEdit.PasswordEchoOnEdit)
        self.password.setDragEnabled(True)
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.gridLayout.addWidget(self.password, 2, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(decrypt)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.ifile = QtWidgets.QLineEdit(decrypt)
        self.ifile.setDragEnabled(True)
        self.ifile.setClearButtonEnabled(True)
        self.ifile.setObjectName("ifile")
        self.gridLayout.addWidget(self.ifile, 0, 1, 1, 1)
        self.key_list = QtWidgets.QLineEdit(decrypt)
        self.key_list.setDragEnabled(True)
        self.key_list.setClearButtonEnabled(True)
        self.key_list.setObjectName("key_list")
        self.gridLayout.addWidget(self.key_list, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(decrypt)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(decrypt)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 4, 0, 1, 1)
        self.browse_key_list = QtWidgets.QPushButton(decrypt)
        self.browse_key_list.setObjectName("browse_key_list")
        self.gridLayout.addWidget(self.browse_key_list, 4, 2, 1, 1)
        self.browse_ifile = QtWidgets.QPushButton(decrypt)
        self.browse_ifile.setObjectName("browse_ifile")
        self.gridLayout.addWidget(self.browse_ifile, 0, 2, 1, 1)
        self.browse_ofile = QtWidgets.QPushButton(decrypt)
        self.browse_ofile.setObjectName("browse_ofile")
        self.gridLayout.addWidget(self.browse_ofile, 1, 2, 1, 1)
        self.checkHashes = QtWidgets.QCheckBox(decrypt)
        self.checkHashes.setObjectName("checkHashes")
        self.gridLayout.addWidget(self.checkHashes, 5, 0, 1, 1)
        self.browse_hashlog = QtWidgets.QPushButton(decrypt)
        self.browse_hashlog.setEnabled(False)
        self.browse_hashlog.setObjectName("browse_hashlog")
        self.gridLayout.addWidget(self.browse_hashlog, 5, 2, 1, 1)
        self.hash_log = QtWidgets.QLineEdit(decrypt)
        self.hash_log.setEnabled(False)
        self.hash_log.setObjectName("hash_log")
        self.gridLayout.addWidget(self.hash_log, 5, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(decrypt)
        QtCore.QMetaObject.connectSlotsByName(decrypt)
        decrypt.setTabOrder(self.ifile, self.ofile)
        decrypt.setTabOrder(self.ofile, self.password)
        decrypt.setTabOrder(self.password, self.private_key)
        decrypt.setTabOrder(self.private_key, self.key_list)
        decrypt.setTabOrder(self.key_list, self.reset)
        decrypt.setTabOrder(self.reset, self.decrypt_file)
        decrypt.setTabOrder(self.decrypt_file, self.browse_ifile)
        decrypt.setTabOrder(self.browse_ifile, self.browse_ofile)
        decrypt.setTabOrder(self.browse_ofile, self.browse_private_Key)
        decrypt.setTabOrder(self.browse_private_Key, self.browse_key_list)

    def retranslateUi(self, decrypt):
        _translate = QtCore.QCoreApplication.translate
        decrypt.setWindowTitle(_translate("decrypt", "Form"))
        self.decrypt_file.setText(_translate("decrypt", "Decrypt"))
        self.reset.setText(_translate("decrypt", "Reset Fields"))
        self.label_3.setText(_translate("decrypt", "Password"))
        self.label_2.setText(_translate("decrypt", "Ofile"))
        self.browse_private_Key.setText(_translate("decrypt", "Browse"))
        self.label_5.setText(_translate("decrypt", "Private Key"))
        self.label.setText(_translate("decrypt", "Infile"))
        self.label_4.setText(_translate("decrypt", "Key List"))
        self.browse_key_list.setText(_translate("decrypt", "Browse"))
        self.browse_ifile.setText(_translate("decrypt", "Browse"))
        self.browse_ofile.setText(_translate("decrypt", "Browse"))
        self.checkHashes.setText(_translate("decrypt", "Use Hash Log"))
        self.browse_hashlog.setText(_translate("decrypt", "Browse"))

