# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/encrypt_widget.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_encrypt(object):
    def setupUi(self, encrypt):
        encrypt.setObjectName("encrypt")
        encrypt.resize(667, 343)
        self.gridLayout_2 = QtWidgets.QGridLayout(encrypt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.browse_ofile = QtWidgets.QPushButton(encrypt)
        self.browse_ofile.setObjectName("browse_ofile")
        self.gridLayout.addWidget(self.browse_ofile, 1, 3, 1, 1)
        self.label = QtWidgets.QLabel(encrypt)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.browse_keylist = QtWidgets.QPushButton(encrypt)
        self.browse_keylist.setObjectName("browse_keylist")
        self.gridLayout.addWidget(self.browse_keylist, 3, 3, 1, 1)
        self.ofile = QtWidgets.QLineEdit(encrypt)
        self.ofile.setDragEnabled(True)
        self.ofile.setClearButtonEnabled(True)
        self.ofile.setObjectName("ofile")
        self.gridLayout.addWidget(self.ofile, 1, 2, 1, 1)
        self.browse_public_key = QtWidgets.QPushButton(encrypt)
        self.browse_public_key.setObjectName("browse_public_key")
        self.gridLayout.addWidget(self.browse_public_key, 2, 3, 1, 1)
        self.public_key = QtWidgets.QLineEdit(encrypt)
        self.public_key.setDragEnabled(True)
        self.public_key.setClearButtonEnabled(True)
        self.public_key.setObjectName("public_key")
        self.gridLayout.addWidget(self.public_key, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(encrypt)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(encrypt)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.key_list = QtWidgets.QLineEdit(encrypt)
        self.key_list.setDragEnabled(True)
        self.key_list.setClearButtonEnabled(True)
        self.key_list.setObjectName("key_list")
        self.gridLayout.addWidget(self.key_list, 3, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(encrypt)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 5, 0, 1, 1)
        self.ifile = QtWidgets.QLineEdit(encrypt)
        self.ifile.setDragEnabled(True)
        self.ifile.setClearButtonEnabled(True)
        self.ifile.setObjectName("ifile")
        self.gridLayout.addWidget(self.ifile, 0, 2, 1, 1)
        self.dataChunkSize = QtWidgets.QSpinBox(encrypt)
        self.dataChunkSize.setMaximum(999999999)
        self.dataChunkSize.setProperty("value", 10485760)
        self.dataChunkSize.setObjectName("dataChunkSize")
        self.gridLayout.addWidget(self.dataChunkSize, 5, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(encrypt)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.browse_ifile = QtWidgets.QPushButton(encrypt)
        self.browse_ifile.setObjectName("browse_ifile")
        self.gridLayout.addWidget(self.browse_ifile, 0, 3, 1, 1)
        self.browse_hash_log = QtWidgets.QPushButton(encrypt)
        self.browse_hash_log.setEnabled(False)
        self.browse_hash_log.setObjectName("browse_hash_log")
        self.gridLayout.addWidget(self.browse_hash_log, 4, 3, 1, 1)
        self.hash_log = QtWidgets.QLineEdit(encrypt)
        self.hash_log.setEnabled(False)
        self.hash_log.setDragEnabled(True)
        self.hash_log.setClearButtonEnabled(True)
        self.hash_log.setObjectName("hash_log")
        self.gridLayout.addWidget(self.hash_log, 4, 2, 1, 1)
        self.useHashes = QtWidgets.QCheckBox(encrypt)
        self.useHashes.setObjectName("useHashes")
        self.gridLayout.addWidget(self.useHashes, 4, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.encrypt_file = QtWidgets.QPushButton(encrypt)
        self.encrypt_file.setObjectName("encrypt_file")
        self.gridLayout_2.addWidget(self.encrypt_file, 4, 0, 1, 1)
        self.progressBar = QtWidgets.QProgressBar(encrypt)
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout_2.addWidget(self.progressBar, 0, 0, 1, 1)
        self.reset = QtWidgets.QPushButton(encrypt)
        self.reset.setObjectName("reset")
        self.gridLayout_2.addWidget(self.reset, 3, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)

        self.retranslateUi(encrypt)
        QtCore.QMetaObject.connectSlotsByName(encrypt)
        encrypt.setTabOrder(self.ifile, self.ofile)
        encrypt.setTabOrder(self.ofile, self.public_key)
        encrypt.setTabOrder(self.public_key, self.key_list)
        encrypt.setTabOrder(self.key_list, self.dataChunkSize)
        encrypt.setTabOrder(self.dataChunkSize, self.encrypt_file)
        encrypt.setTabOrder(self.encrypt_file, self.reset)
        encrypt.setTabOrder(self.reset, self.browse_ifile)
        encrypt.setTabOrder(self.browse_ifile, self.browse_ofile)
        encrypt.setTabOrder(self.browse_ofile, self.browse_public_key)
        encrypt.setTabOrder(self.browse_public_key, self.browse_keylist)

    def retranslateUi(self, encrypt):
        _translate = QtCore.QCoreApplication.translate
        encrypt.setWindowTitle(_translate("encrypt", "Form"))
        self.browse_ofile.setText(_translate("encrypt", "Browse"))
        self.label.setText(_translate("encrypt", "Input"))
        self.browse_keylist.setText(_translate("encrypt", "Browse"))
        self.browse_public_key.setText(_translate("encrypt", "Browse"))
        self.label_4.setText(_translate("encrypt", "Key List"))
        self.label_3.setText(_translate("encrypt", "Public Key"))
        self.label_5.setText(_translate("encrypt", "Data Chunk Size"))
        self.label_2.setText(_translate("encrypt", "OutPut"))
        self.browse_ifile.setText(_translate("encrypt", "Browse"))
        self.browse_hash_log.setText(_translate("encrypt", "Browse"))
        self.useHashes.setText(_translate("encrypt", "Use Hash Log"))
        self.encrypt_file.setText(_translate("encrypt", "Encrypt"))
        self.reset.setText(_translate("encrypt", "Reset Fields"))

