# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/lib_ewk_gui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ewk_gui(object):
    def setupUi(self, ewk_gui):
        ewk_gui.setObjectName("ewk_gui")
        ewk_gui.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(ewk_gui)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName("tabWidget")
        self.encrypt = QtWidgets.QWidget()
        self.encrypt.setObjectName("encrypt")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.encrypt)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.scrollArea = QtWidgets.QScrollArea(self.encrypt)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 754, 483))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.encrypt_layout = QtWidgets.QGridLayout()
        self.encrypt_layout.setObjectName("encrypt_layout")
        self.gridLayout_6.addLayout(self.encrypt_layout, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout_3.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tabWidget.addTab(self.encrypt, "")
        self.decrypt = QtWidgets.QWidget()
        self.decrypt.setObjectName("decrypt")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.decrypt)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.scrollArea_2 = QtWidgets.QScrollArea(self.decrypt)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 754, 483))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.decrypt_layout = QtWidgets.QGridLayout()
        self.decrypt_layout.setObjectName("decrypt_layout")
        self.gridLayout_10.addLayout(self.decrypt_layout, 0, 0, 1, 1)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_2)
        self.gridLayout_7.addWidget(self.scrollArea_2, 0, 0, 1, 1)
        self.gridLayout_8.addLayout(self.gridLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.decrypt, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        ewk_gui.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ewk_gui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        ewk_gui.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ewk_gui)
        self.statusbar.setObjectName("statusbar")
        ewk_gui.setStatusBar(self.statusbar)
        self.action_Quit = QtWidgets.QAction(ewk_gui)
        self.action_Quit.setObjectName("action_Quit")
        self.menuFile.addAction(self.action_Quit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(ewk_gui)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(ewk_gui)

    def retranslateUi(self, ewk_gui):
        _translate = QtCore.QCoreApplication.translate
        ewk_gui.setWindowTitle(_translate("ewk_gui", "EncryptWithKey"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.encrypt), _translate("ewk_gui", "Encrypt"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.decrypt), _translate("ewk_gui", "Decrypt"))
        self.menuFile.setTitle(_translate("ewk_gui", "&File"))
        self.action_Quit.setText(_translate("ewk_gui", "&Quit"))
        self.action_Quit.setShortcut(_translate("ewk_gui", "Ctrl+Q"))

