# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/tabdefaults_decrypt.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_tabdefaults_decrypt(object):
    def setupUi(self, tabdefaults_decrypt):
        tabdefaults_decrypt.setObjectName("tabdefaults_decrypt")
        tabdefaults_decrypt.resize(578, 416)
        self.gridLayout_2 = QtWidgets.QGridLayout(tabdefaults_decrypt)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea = QtWidgets.QScrollArea(tabdefaults_decrypt)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 556, 394))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.browse_ifile = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browse_ifile.setObjectName("browse_ifile")
        self.gridLayout_3.addWidget(self.browse_ifile, 0, 3, 1, 1)
        self.label = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.ifile = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ifile.setObjectName("ifile")
        self.gridLayout_3.addWidget(self.ifile, 0, 2, 1, 1)
        self.key_list = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.key_list.setObjectName("key_list")
        self.gridLayout_3.addWidget(self.key_list, 2, 2, 1, 1)
        self.browse_hash_log = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browse_hash_log.setObjectName("browse_hash_log")
        self.gridLayout_3.addWidget(self.browse_hash_log, 7, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.browse_key_list = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browse_key_list.setObjectName("browse_key_list")
        self.gridLayout_3.addWidget(self.browse_key_list, 2, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_6.setObjectName("label_6")
        self.gridLayout_3.addWidget(self.label_6, 7, 0, 1, 1)
        self.hash_log = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.hash_log.setObjectName("hash_log")
        self.gridLayout_3.addWidget(self.hash_log, 7, 2, 1, 1)
        self.browse_ofile = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browse_ofile.setObjectName("browse_ofile")
        self.gridLayout_3.addWidget(self.browse_ofile, 1, 3, 1, 1)
        self.password = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.password.setObjectName("password")
        self.gridLayout_3.addWidget(self.password, 5, 2, 1, 1)
        self.browse_private_key = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.browse_private_key.setObjectName("browse_private_key")
        self.gridLayout_3.addWidget(self.browse_private_key, 3, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_5.setObjectName("label_5")
        self.gridLayout_3.addWidget(self.label_5, 5, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.scrollAreaWidgetContents)
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.ofile = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.ofile.setObjectName("ofile")
        self.gridLayout_3.addWidget(self.ofile, 1, 2, 1, 1)
        self.private_key = QtWidgets.QLineEdit(self.scrollAreaWidgetContents)
        self.private_key.setObjectName("private_key")
        self.gridLayout_3.addWidget(self.private_key, 3, 2, 1, 1)
        self.password_actions = QtWidgets.QPushButton(self.scrollAreaWidgetContents)
        self.password_actions.setEnabled(False)
        self.password_actions.setObjectName("password_actions")
        self.gridLayout_3.addWidget(self.password_actions, 5, 3, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.gridLayout.addWidget(self.scrollArea, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(tabdefaults_decrypt)
        QtCore.QMetaObject.connectSlotsByName(tabdefaults_decrypt)

    def retranslateUi(self, tabdefaults_decrypt):
        _translate = QtCore.QCoreApplication.translate
        tabdefaults_decrypt.setWindowTitle(_translate("tabdefaults_decrypt", "Form"))
        self.browse_ifile.setText(_translate("tabdefaults_decrypt", "Browse"))
        self.label.setText(_translate("tabdefaults_decrypt", "Infile"))
        self.browse_hash_log.setText(_translate("tabdefaults_decrypt", "Browse"))
        self.label_3.setText(_translate("tabdefaults_decrypt", "Key List"))
        self.browse_key_list.setText(_translate("tabdefaults_decrypt", "Browse"))
        self.label_6.setText(_translate("tabdefaults_decrypt", "Hash Log"))
        self.browse_ofile.setText(_translate("tabdefaults_decrypt", "Browse"))
        self.browse_private_key.setText(_translate("tabdefaults_decrypt", "Browse"))
        self.label_4.setText(_translate("tabdefaults_decrypt", "Private Key"))
        self.label_5.setText(_translate("tabdefaults_decrypt", "Password"))
        self.label_2.setText(_translate("tabdefaults_decrypt", "Ofile"))
        self.password_actions.setText(_translate("tabdefaults_decrypt", "?"))


